# permissions for end users to edit sinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sink-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: analytic-controller
    app.kubernetes.io/part-of: analytic-controller
    app.kubernetes.io/managed-by: kustomize
  name: sink-editor-role
rules:
- apiGroups:
  - analytics.weave.works
  resources:
  - sinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - analytics.weave.works
  resources:
  - sinks/status
  verbs:
  - get
